name: Run After File List Workflow

on:
  workflow_run:
    workflows: ["List Changed Files"]
    types:
      - completed

jobs:
  continue-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Confirm trigger
        run: echo "Workflow 2 triggered after Workflow 1 completed successfully"
