name: List Changed Files

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get list of changed files
               id: changed-files
        run: |
          files=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$files"
          # Save properly formatted multi-line output
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
