name: List Changed Files

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get list of changed files
        id: changed-files
        run: |
          files=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$files"
          echo "files=$files" >> $GITHUB_OUTPUT
